### PR TITLE
Support docker and Unix Domain socket mounts

### PR DESCRIPTION
**Pull request by huntc**
Also, updated the README having re-run through its flow.

Works on both Linux and OS X.

### CODE REVIEW

**Comment by longshorej** [comment]
I ran through this and it worked with some tweaks required:

The socket itself was owned by uid 0 / gid 0 since it was created inside the container (even though the parent dir is owned by my current user), so running the client on my host it couldn't connect until adjusting permissions after starting the container. Perhaps we could use ACLs on linux to work around that.

I successfully ran the client in a container with the following:

```bash
# start the container
docker run -t -i --rm \
  --mount "type=bind,source=$PWD/landlord/target/release,target=/usr/local/bin" --mount type=bind,source=/var/run/landlord,target=/var/run/landlord \
  --mount "type=bind,source=$PWD/landlordd/test/target/scala-2.12,target=/opt/test" \
  debian:9 /bin/bash

# and the in the container
echo Testing... | landlord -cp /opt/test/classes -Dgreeting=Welcome example.Hello ArgOne ArgTwo
Argument #1: ArgOne
Argument #2: ArgTwo
Welcome
Testing...
Good Bye!

```

**Comment by huntc** [comment]
Thanks. I was thinking that you could run landlordd with cpu constraints to mix things up a bit. 

Any chance you could PR my PR to explain how the client and daemon are able to run?

**Comment by huntc** [comment]
I’m mixing up my PRs here. Forget what I said about cpu tweaks here. However if you could push another commit on this PR or raise another then that’d be awesome. Thanks.

**Comment by longshorej** [comment]
After playing with this some more (in an attempt to ammend this PR), I think we should ensure that the socket is created as owner/group/everyone read/write permissions. This is only needed when running in Docker, so as part of our Docker image we can run `umask 002` prior to starting the JVM. Thus, usage doesn't chage from what you've documented.

WDYT @huntc?

**Comment by huntc** [comment]
I may not understand, but given:

```
$ docker exec -it 13c15243a840 ls -al /var/run/landlord
total 4
drwxr-xr-x    3 root     root            96 Jun  3 06:55 .
drwxr-xr-x    1 root     root          4096 Jun  1 08:12 ..
srwxrwxrwx    1 root     root             0 Jun  3 06:55 landlordd.sock
```

...so it seems that the permissions are already correctly set...

**Comment by huntc** [comment]
@longshorej The following should work for you (I tested on my local Linux machine):

Set up the shared socket directory:

```
sudo mkdir -p /var/run/landlord
sudo chown $LOGNAME /var/run/landlord
setfacl -m "u:2:rwx" /var/run/landlord # UID 2 is the daemon user within the container
```

Run the daemon:

```
docker run \
  -it \
  --rm  \
  --mount type=bind,source=/var/run/landlord,target=/var/run/landlord \
  landlord/daemon:latest
```

Then, from another terminal, run the hello app:

```
docker run \
  --rm \
  --mount type=bind,source=/var/run/landlord,target=/var/run/landlord \
  landlord/hello
```

The problem for us is that socket sharing is unsupported on OS X and I think will be a challenge on IOx. IOx doesn't actually run Docker, but converts its container image layers for use with LXC. I've not yet found a command that shares the host file system as per `--mount`. There's a chance that the USB mount could be used, but I'm not sure.

I'm beginning to wonder whether we could use `socat`, or as per Docker, also support TCP for comms. Landlord originally had support for TCP which I replaced with Unix Domain Sockets given their strengthened security. :-P I carefully designed the UDS API to look exactly like the TCP one within landlord so that wouldn't be hard, and perhaps the Rust client wouldn't be that hard either...?

If we go down the TLS path though, then perhaps we'll need mutual TLS auth...

**Comment by longshorej** [comment]
Thanks - that does work. I have a small suggestion to make it a bit more idiomatic Docker (understanding we aren't using this on IOx):

Using Docker volumes (i.e. I didn't have to setup a directory ahead of time, but rather create a volume):

```bash
docker volume create landlord --driver local --opt type=tmpfs --opt device=tmpfs --opt o=uid=2
landlord
-> 0

docker run --rm -v landlord:/var/run/landlord landlord/daemon
Slf4jLogger started
Ready.
```

```bash
docker run --rm -v landlord:/var/run/landlord landlord/hello
Argument #1: ArgOne
Argument #2: ArgTwo
Welcome
Good Bye!
-> 0

```

For our situation, TCP bound to localhost might be enough? Would we really need TLS?

**Comment by huntc** [comment]
Yeah, happy with the UX. Agree on the rpm/Deb etc. I favour anything that removes the barriers to entry.

**Pull request merged**
