### PR TITLE
rust 1.27.0

### PR DESCRIPTION
**Pull request by longshorej**
[Rust 1.27.0](https://blog.rust-lang.org/2018/06/21/Rust-1.27.html)

### CODE REVIEW

**Comment by dwijnand** [comment]
Btw, why the version pin?

**Comment by huntc** [comment]
@dwijnand Is this a trick question? ;-)

My answer would be so that we can ensure a stable build - as per specifying the Scala compiler version in a `build.sbt`.

...or do I misunderstand the question? :-)

**Comment by longshorej** [comment]
Yeah, just being explicit so that rustup can ensure the proper toolchain is active.

**Comment by dwijnand** [comment]
I just wanted to guage your take on it.

My understanding is Rust is committed to backwards compatibility, and a hypothetical backwards-breaking "Rust 2" will never happen (it'll rather be another language). At that point maintaining a version is just maintainable burden.

**Comment by longshorej** [comment]
Yeah, I think if a given machine has a newer version we'd be okay. If the dev machine has an older version installed, that would be a problem though right? i.e. there's (naturally) no forward compatibility

**Comment by longshorej** [comment]
(assuming we're using newer features/apis of course)

**Comment by dwijnand** [comment]
Yes, correct.

**Pull request merged**
