### PR TITLE
Introducing the classloader approach

### PR DESCRIPTION
**Pull request by huntc**
Having now abandoned the process forking approach as it didn't save enough memory (see #1's description), I'm now emulating the forking of a process within the same JVM i.e. provide:

* a new classloader for each process that prohibits looking up landlord's and other process classes (similar to OSGi I imagine)
* a security manager for each process
* stream redirection for each process
* properties for each process (including an updated and distinct user.dir)

Internally, I've introduced a `ThreadGroupMapping` trait that keeps track of the above-associated objects in the context of the thread group that is current for the thread. All new processes are created with their own thread group.

Note a key feature here: Both Nailgun and OSGi place a burden on the developer, particularly the latter. The approach I've taken here attempts to minimise that burden, requiring very few source code changes. Any changes that are necessary should be easily comprehended. In addition, the source code must work unchanged whether running via landlord or not.

Given that I cannot reliably detect when a thread group's threads have all terminated, there is a requirement on the developer to now call `System.exit(status)` when exiting - even with a `0` status code. If the developer doesn't call `System.exit` then their process will not exit. This is more flexible, but also consistent with C, C++ and others where a status code must be returned from the main function.

In addition, we warn about the adding of shutdown handlers given that they unavoidably apply to a process as a whole. Instead, a new `trap` function can be provided in place of shutdown handlers. Any signals passed to the process will be raised through this function. The `trap` function is declared as follows and must appear in the same class as the `main` function. Here is a full example in Java. The full example below permits both running within and outside of landlord:

```java
package example;

import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.io.IOException;

public class Hello {
    public static void main(String[] args) throws IOException {
        try {
            Runtime.getRuntime().addShutdownHook(new Thread(() -> System.out.println("Shutdown trapped")));
        } catch (SecurityException ignored) {
            // An exception will be thrown when running via landlord started with --prevent-shutdown-hooks
        }

        BufferedReader br = new BufferedReader(new InputStreamReader(System.in));
        System.out.println(br.readLine());
        System.exit(0);
    }

    @SuppressWarnings("unused")
    public static void trap(int signal) {
        System.out.println("Trapped: " + signal);
        if ((signal & 0xf) > 0)             // Terminate
          System.exit(128 + signal); // As per the convention of exit codes
    }
}
```

The only downside that I can think about regarding the approach is that a process can screw up the JVM for all processes. This is the price to pay for a multi-tenanted JVM though without creating my own JVM. Besides which, it is no different in this regard to Nailgun, OSGi at large and the now-defunct Applets of another time.

I cannot think of a better way to save memory than this approach, or again, patching an existing JVM. Profiling via VisualVM is encouraging in terms of highlighting memory usage. I performed a heap dump while the Hello World program was running and noticed that the retained size of its URLClassLoader is just 6KiB - add another 512KiB for stack-space, JIT native code generation (how to measure this size - probably smaller than 6KiB?). Let's say < 1MiB all up. Compare this to about 35MiB via the forking approach i.e. more than a 30x improvement on memory savings.

### CODE REVIEW

**Comment by huntc** [comment]
FYI @longshortj, @fsat and @jousby

**Comment by huntc** [comment]
I've now verified that the `example.Hello` world class is unloaded. To reproduce:

1. Launch with the following flags: `JAVA_OPTS="-XX:+TraceClassUnloading -XX:MaxMetaspaceSize=32m"; daemon/target/universal/stage/bin/landlordd  --process-dir-path=/tmp/a --prevent-shutdown-hooks`
2. Use VisualVM (or equiv), attach to process
3. Run the `client.sh` script
4. Hit the "Perform GC" button to force a GC
5. You should see something like:

```
[Unloading class example.Hello$$Lambda$443/1451820752 0x00000007c0437428]
[Unloading class example.Hello 0x00000007c0437c28]
```

**Comment by huntc** [comment]
Profiling via VisualVM is encouraging in terms of highlighting memory usage. I performed a heap dump while the Hello World program was running and noticed that the retained size of its URLClassLoader is just 6KiB. Compare this to about 35MiB via the forking approach (yes, KiB vs MiB!).

**Comment by huntc** [comment]
@retronym - Any thoughts on this? Think OSGi without the burden on the developer... I'm curious as to what you think in particular regarding the last para:

I cannot think of a better way to save memory than this approach, or again, patching an existing JVM. Profiling via VisualVM is encouraging in terms of highlighting memory usage. I performed a heap dump while the Hello World program was running and noticed that the retained size of its URLClassLoader is just 6KiB - add another 512KiB for stack-space, JIT native code generation (how to measure this size - probably smaller than 6KiB?). Let's say < 1MiB all up. Compare this to about 35MiB via the forking approach i.e. more than a 30x improvement on memory savings.

**Comment by retronym** [comment]
>  JIT native code generation (how to measure this size

I think Native Memory Tracking is the tool for this job, which is explored by [Shipilev](https://shipilev.net/jvm-anatomy-park/12-native-memory-tracking/) in a quest to attribute footprint to VM infrastructure.

As you've seen from AliJVM presentation at JVMLS, multi-tenancy can introduce headaches because of inability to quota the heap and the inability to reason about how JIT and GC works for the aggregate JVM.

If you do opt for multi-tenancy, you can use tiered classloaders for common sets of JARs, e.g. a bunch of tenants based on Scala 2.12.4 could have them in a parent classloader to share the fruits of JIT's labours. I think CBT does something like this.

OSGi is solving a harder problem in some respects: it provides isolation with specified sharing of interfaces. So it is likely that if you are after full isolation, you can have a simpler model than OSGi. But it would make sense to learn as much as possible from the OSGi spec and implementation before moving on!

It is worth noting that Oracle is in the process of open sourcing Application CDS, which can slightly move the needle for the best case footprint of a multi-JVM deployment.

An important thing to consider is whether the landlord or the tenants are in control on the threads. If the heap requirements are low, the next dominant factor in footprint is thread stacks. If each tenant creates a thread pool, many of the gains of communal living are gone.

All of this points to the need to model the footprint of an application (or a set of applications) based on: 
  - number of threads (which could be amortized to 0 if it is willing to use the landlord's threadpool)
  - stack size requirement
  - retained heap size (maximum, or even better, distribution)

**Comment by retronym** [comment]
> Q: Does the JIT index its work then by classloader?

Yep, if you have a given class in more than one classloader, JIT will see them separately.

Cons: more work for JIT to do, and more footprint for the compiled code and bookkeeping.
Pros: an individual tenant _might_ get better performance in hot paths because JIT makes choices based on only that tenant's usage patterns, which might allow more aggressive inlining.

**Pull request merged**
